services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./data/temp:/tmp/shared
      - ./init/setup_db.sh:/docker-entrypoint-initdb.d/setup_db.sh
    networks:
      - mpc-postgresql 

  dbhub:
    image: bytebase/dbhub
    container_name: dbhub
    ports:
      - "8080:8080"
    command:
      - "--transport"
      - "sse"
      - "--port"
      - "8080"
      - "--dsn"
      - "${DB_DSN}"
    init: true
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - mpc-postgresql

networks:
  mpc-postgresql:
    driver: bridge
